Repository character-map-uwp/Character-Map-UWP, pull requests merged in 2020-02, with the labels that each got.

#59 User collections
  0_artifacts/StoreListing.en.md
  CharacterMap/CharacterMap/CharacterMap.csproj
  CharacterMap/CharacterMap/Controls/CreateCollectionDialog.xaml
  CharacterMap/CharacterMap/Controls/CreateCollectionDialog.xaml.cs
  CharacterMap/CharacterMap/Core/AppSettings.cs
  CharacterMap/CharacterMap/Core/CollectionsUpdatedMessage.cs
  CharacterMap/CharacterMap/Core/Converters.cs
  CharacterMap/CharacterMap/Core/FontFinder.cs
  CharacterMap/CharacterMap/Core/FontVariant.cs
  CharacterMap/CharacterMap/Core/PanoseFamily.cs
  CharacterMap/CharacterMap/Core/PanoseParser.cs
  CharacterMap/CharacterMap/Core/SerifStyle.cs
  CharacterMap/CharacterMap/Helpers/FlyoutHelper.cs
  CharacterMap/CharacterMap/Helpers/Json.cs
  CharacterMap/CharacterMap/Helpers/ResourceHelper.cs
  CharacterMap/CharacterMap/Services/UserCollectionsService.cs
  CharacterMap/CharacterMap/Strings/en-US/Resources.resw
  CharacterMap/CharacterMap/ViewModels/FontMapViewModel.cs
  CharacterMap/CharacterMap/ViewModels/MainViewModel.cs
  CharacterMap/CharacterMap/ViewModels/ViewModelLocator.cs
  CharacterMap/CharacterMap/Views/FontMapView.xaml
  CharacterMap/CharacterMap/Views/FontMapView.xaml.cs
  CharacterMap/CharacterMap/Views/MainPage.xaml
  CharacterMap/CharacterMap/Views/MainPage.xaml.cs
Labels: enhancement

#61 Improve support for fonts with technically invalid character ranges
  CharacterMap/CharacterMap/Core/FontVariant.cs
  CharacterMap/CharacterMap/Core/PanoseParser.cs
  CharacterMap/CharacterMap/ViewModels/MainViewModel.cs
  CharacterMap/CharacterMap/Views/MainPage.xaml.cs
Labels: bug

#63 Potential fix
  CharacterMap/CharacterMap/Core/FontVariant.cs
Labels: bug

#65 Update Simplified Chinese Resources
  CharacterMap/CharacterMap/Package.appxmanifest
  CharacterMap/CharacterMap/Strings/de-DE/Resources.resw
  CharacterMap/CharacterMap/Strings/fr-FR/Resources.resw
  CharacterMap/CharacterMap/Strings/pl-PL/Resources.resw
  CharacterMap/CharacterMap/Strings/ru-RU/Resources.resw
  CharacterMap/CharacterMap/Strings/zh-CN/Resources.resw
  CharacterMap/CharacterMap/Strings/zh-TW/Resources.resw
Labels: localization

#66 Extra props, export of raw PNG / SVG glyphs, perf improvements
  CharacterMap/CharacterMap.CX/CanvasTextLayoutAnalysis.cpp
  CharacterMap/CharacterMap.CX/CanvasTextLayoutAnalysis.h
  CharacterMap/CharacterMap.CX/CharacterMap.CX.vcxproj
  CharacterMap/CharacterMap.CX/CharacterMap.CX.vcxproj.filters
  CharacterMap/CharacterMap.CX/ColorTextAnalyzer.cpp
  CharacterMap/CharacterMap.CX/ColorTextAnalyzer.h
  CharacterMap/CharacterMap.CX/DWHelpers.h
  CharacterMap/CharacterMap.CX/DWriteFontFace.h
  CharacterMap/CharacterMap.CX/DWriteFontSet.h
  CharacterMap/CharacterMap.CX/DWriteFontSource.h
  CharacterMap/CharacterMap.CX/DWriteProperties.h
  CharacterMap/CharacterMap.CX/Interop.cpp
  CharacterMap/CharacterMap.CX/Interop.h
  CharacterMap/CharacterMap.CX/SVGGeometrySink.h
  CharacterMap/CharacterMap/CharacterMap.csproj
  CharacterMap/CharacterMap/Controls/CreateCollectionDialog.xaml
  CharacterMap/CharacterMap/Core/Character.cs
  CharacterMap/CharacterMap/Core/CollectionsUpdatedMessage.cs
  CharacterMap/CharacterMap/Core/Converters.cs
  CharacterMap/CharacterMap/Core/ExportManager.cs
  CharacterMap/CharacterMap/Core/FontFinder.cs
  CharacterMap/CharacterMap/Core/FontVariant.cs
  CharacterMap/CharacterMap/Core/Messages.cs
  CharacterMap/CharacterMap/Core/Utils.cs
  CharacterMap/CharacterMap/Provider/SQLiteGlyphProvider.cs
  CharacterMap/CharacterMap/Services/GlyphService.cs
  CharacterMap/CharacterMap/Services/UserCollectionsService.cs
  CharacterMap/CharacterMap/Strings/en-GB/Resources.resw
  CharacterMap/CharacterMap/Strings/en-US/Resources.resw
  CharacterMap/CharacterMap/Styles/Button.xaml
  CharacterMap/CharacterMap/ViewModels/FontMapViewModel.cs
  CharacterMap/CharacterMap/ViewModels/MainViewModel.cs
  CharacterMap/CharacterMap/Views/FontMapView.xaml
  CharacterMap/CharacterMap/Views/FontMapView.xaml.cs
  CharacterMap/CharacterMap/Views/MainPage.xaml
  CharacterMap/CharacterMap/Views/MainPage.xaml.cs
  CharacterMap/Settings.XamlStyler
Labels: enhancement
